version: '3.1'
services:
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: dbPostgres
  # dbPostgres:
  #   image: postgres:10
  #   restart: always
  #   ports:
  #   - 5432:5432
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: changeme
  #     POSTGRES_DB: mydb